name: Update OpenAPI

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-openapi

jobs:
  example_job:
    runs-on: ubuntu-latest

    env:
      ENV_VARIABLE: ${{ secrets.MY_SECRET }}

    steps:
      - name: Print Secret
        run: echo $ENV_VARIABLE
