name: Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Approve PR
      if: github.head_ref == 'ga/update-openapi'
      run: |
        gh auth login --with-token <<< "${{ secrets.REPO_ACCESS_TOKEN }}"
        gh pr review ${{ github.event.pull_request.number }} --approve
      env:
        GH_CLI_FORCE_COLOR: 1

    - name: Auto Merge PR
      if: github.head_ref == 'ga/update-openapi'
      run: |
        gh auth login --with-token <<< "${{ secrets.REPO_ACCESS_TOKEN }}"
        gh pr merge ${{ github.event.pull_request.number }} --auto --merge
      env:
        GH_CLI_FORCE_COLOR: 1
